meta_product_name: "Active Potato"
meta_title: "Active Potato - Connect easily with sporty people "
meta_description: "Digital Platform that allow young sporty people to find sport partners "
meta_image: "logo.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
